### ISSUE TITLE
Maintainers

### ISSUE THREAD

**Issue by rwwagner90** [shipshapecode/ember-cli-release#68]
Is this still actively maintained? I see the code hasn't changed in a couple years. I would love to give this some new life and take over maintenance under https://github.com/shipshapecode or https://github.com/html-next.

**Comment by rwwagner90** [comment]
@humanchimp would you mind transferring to the Ship Shape org then? https://github.com/shipshapecode

If so, I can start getting to work on it and get my team working on it as well.

I can make you and whoever else should be owners of the repo as well.

**Comment by humanchimp** [comment]
i'm gonna need permission to create the repo in your org

**Comment by rwwagner90** [comment]
Thanks for transferring @humanchimp! I'll be working on this more in the coming weeks. I may also need access on npm. Could you add me as a collaborator there please? I'm rwwagner90 on there as well.
