### ISSUE TITLE
This addon seems to be unmaintained - alternative: ember-cli-release-tag

### ISSUE THREAD

**Issue by mydea** [shipshapecode/ember-cli-release#77]
Since this addon seems to be unmaintained, and dependencies are woefully out of date, I made a forked, modernized version of this, [ember-cli-release-tag](https://github.com/mydea/ember-cli-release-tag).

Since there have been no responses to any issues and PRs for months (or years), and we do use that functionality somewhat often, I decided to make a mostly drop-in replacement with a more modern codebase and dependencies.

For now, this new addon is a bit streamlined and I have removed some options:

- The `date` strategy does not accept any additional arguments anymore - it is always `v19.01.16`. Feel free to provide your own custom strategy if needed.
- NPM publishing is not included right now
- For semver, `premajor` and `preminor` have been dropped. Instead, always use `prerelease`, which you can combine with `major` (--> pre-major) or `minor` (--> pre-minor), e.g. `ember release --major --prerelease='beta'`
- You have to confirm before the release commit is created (see #67)

See #71 , #72, #69 

For most common use cases, it should be enough to do 

```
yarn remove ember-cli-release
yarn add ember-cli-release-tag
```

And continue as before.

**Comment by rwjblue** [comment]
FWIW, I personally use `release-it` (along with `lerna-changelog`) these days. I made a handy dandy boostrapping package to make it easier to get started (`npm init rwjblue-release-it-setup`):

https://github.com/rwjblue/create-rwjblue-release-it-setup

**Comment by rwwagner90** [comment]
@mydea would you be interested in helping merge that functionality in here, rather than forking? I'm happy to add you as a maintainer.

**Comment by jacobq** [comment]
@rwwagner90 FWIW there is also [`adopted-ember-addons`](https://github.com/adopted-ember-addons) ([more info](https://github.com/adopted-ember-addons/program-guidelines/blob/master/README.md)) if you find that you don't have time to maintain the addon but want it to continue living on for those using it.

**Comment by mydea** [comment]
I could try to add my changes here, but it is basically a complete re-write which tries to keep a similar (but not 100% matching) API surface.

Overall, I wonder if it is worth it, vs. just recommending to use `release-it` as @rwjblue recommended - which is a non-Ember specific solution to this problem, which actually also offers even more functionality. Maybe we should push the community to use that instead...?

**Comment by jelhan** [comment]
> Overall, I wonder if it is worth it, vs. just recommending to use `release-it` as @rwjblue recommended - which is a non-Ember specific solution to this problem, which actually also offers even more functionality. Maybe we should push the community to use that instead...?

Just started to use `release-it` the first time. It has a ton of features I missed on `ember-cli-release`. I think it's time to drop another ember-specific solution in favor of the established tool in the non-ember world.

**Comment by rwwagner90** [comment]
I could be in favor of suggesting release-it. Never used it before myself, but if @rwjblue likes it, it must be okay 😃

**Comment by elwayman02** [comment]
`release-it` is fantastic, this RB is a great template for how to quickly and easily add it to any project:

https://github.com/ember-modifier/ember-modifier/pull/16
